version: 2

updates:

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
    labels:
      - "kind/dependencies"
      - "bot"
    open-pull-requests-limit: 10
    target-branch: devel

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "11:00"
    labels:
      - "area/ci"
      - "github_actions"
      - "kind/dependencies"
      - "bot"
    open-pull-requests-limit: 10
    target-branch: devel

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "11:00"
    labels:
      - "kind/dependencies"
      - "bot"
    open-pull-requests-limit: 10
    target-branch: devel
