ans = {
    'lex1': [
        ('title', 'Title card', 1), ('separator', '\n', 1),
        ('int_number', 1, 2), ('int_number', 1, 2), ('-', '-', 2),
        ('flt_number', 1.0, 2), ('int_number', 1, 2), ('int_number', 2, 2),
        ('+', '+', 2), ('int_number', 3, 2), ('IMP', 'imp', 2), (':', ':', 2),
        ('N', 'n', 2), ('int_number', 1, 2), ('separator', '\n', 2),
        ('int_number', 2, 3), ('void_material', '0', 3), ('int_number', 1, 3),
        ('-', '-', 3), ('int_number', 2, 3), ('int_number', 3, 3),
        ('IMP', 'imp', 3), (':', ':', 3), ('P', 'p', 3), ('int_number', 0, 3),
        ('separator', '\n', 3),
        ('int_number', 3, 4), ('void_material', '0', 5), ('int_number', 1, 5),
        ('int_number', 2, 5), ('int_number', 3, 5), ('int_number', 4, 6),
        ('int_number', 5, 6), ('separator', '\n', 6),
        ('int_number', 4, 7), ('int_number', 2, 7), ('-', '-', 7),
        ('int_number', 5, 7), ('int_number', 1, 7), ('VOL', 'vol', 8),
        ('int_number', 1, 8), ('separator', '\n', 8),
        ('int_number', 5, 9), ('void_material', '0', 9), ('-', '-', 9),
        ('int_number', 1, 9), ('int_number', 2, 9), ('blank_line', '\n', 9),
        ('int_number', 1, 11), ('surface_type', 'PX', 11), ('-', '-', 11),
        ('flt_number', 1.0, 11), ('separator', '\n', 11),
        ('int_number', 2, 12), ('surface_type', 'C/Y', 12),
        ('flt_number', 2.e-2, 12), ('-', '-', 12), ('flt_number', 0.3, 12),
        ('flt_number', 400, 12), ('blank_line', '\n', 12),
        ('MODE', 'mode', 14), ('N', 'n', 14), ('separator', '\n', 14),
        ('VOL', 'vol', 15), ('int_number', 1, 15), ('int_number', 2, 15),
        ('blank_line', '\n', 15)
    ],
    'lex2': [
        ('title', 'Title card', 1), ('separator', '\n', 3),
        ('int_number', 1, 4), ('int_number', 1, 4), ('-', '-', 4),
        ('flt_number', 1.0, 4), ('int_number', 1, 4), ('int_number', 2, 4),
        ('+', '+', 4), ('int_number', 3, 4), ('IMP', 'imp', 4), (':', ':', 4),
        ('N', 'n', 4), ('int_number', 1, 4), ('separator', '\n', 5),
        ('int_number', 2, 6), ('void_material', '0', 6), ('int_number', 1, 6),
        ('-', '-', 6), ('int_number', 2, 6), ('int_number', 3, 9),
        ('IMP', 'imp', 9), (':', ':', 9), ('P', 'p', 9), ('int_number', 0, 9),
        ('separator', '\n', 9),
        ('int_number', 3, 10), ('void_material', '0', 11), ('int_number', 1, 11),
        ('int_number', 2, 11), ('int_number', 3, 11), ('int_number', 4, 12),
        ('int_number', 5, 12), ('separator', '\n', 12),
        ('int_number', 4, 13), ('int_number', 2, 13), ('-', '-', 13),
        ('int_number', 5, 13), ('int_number', 1, 13), ('VOL', 'vol', 14),
        ('int_number', 1, 14), ('separator', '\n', 14),
        ('int_number', 5, 15), ('void_material', '0', 15), ('-', '-', 15),
        ('int_number', 1, 15), ('int_number', 2, 15), ('blank_line', '\n', 16),
        ('int_number', 1, 20), ('surface_type', 'PX', 20), ('-', '-', 20),
        ('flt_number', 1.0, 20), ('separator', '\n', 20),
        ('int_number', 2, 21), ('surface_type', 'C/Y', 21),
        ('flt_number', 2.e-2, 21), ('-', '-', 21), ('flt_number', 0.3, 21),
        ('flt_number', 400, 21), ('blank_line', '\n', 21),
        ('MODE', 'mode', 23), ('N', 'n', 23), ('separator', '\n', 23),
        ('VOL', 'vol', 24), ('int_number', 1, 24), ('int_number', 2, 24),
        ('separator', '\n', 24),
        ('M', 'm', 25), ('int_number', 1, 25), ('int_number', 1001, 25),
        ('.', '.', 25), ('int_number', 50, 25), ('C', 'c', 25),
        ('blank_line', '\n', 26)
    ]
}
