#!/bin/bash

. ~/.bash-functions.rc

# set -exu
# set -e


reset() {
    local envs=( $(pyenv local) )
    local env="${envs[0]}"

    [[ -z "$env" ]] && die "Cannot define target pyenv environment."

    local pkgs=( $(ls src) )
    local pkg=${pkgs[0]}
    local last_python="3.11.3"

    echo "Installing package $pkg to environment $env with python $last_python."

    eval "$(pyenv init -)"
    pyenv local "$last_python"
    pyenv virtualenv-delete -f  "$env" && echo "Removed environment $env"
    pyenv virtualenv "$last_python" "$env" && echo "Created environment $env"
    pyenv rehash
    pyenv shell "$env"
    pyenv local "$env"
    poetry env info
    poetry install

    python -c "import ${pkg}; print(${pkg}.__version__)" && success "Environment $env is reset"

    pyenv shell --unset
    pyenv local "$env" "3.10.11" "3.9.16" "3.8.16"
    pyenv rehash
}

reset  "$@"

# vim: set ts=4 sw=4 tw=92 ss=0 ft=sh et ai :
